[tool.poetry]
name = "pyproject"
version = "0.1.0"
description = ""
authors = ["Raquel Reis <raquelreis233@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.5.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
